name: Build Container CI

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  
  webservice:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container for service
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          # file: frontend.Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}
      - name: Build container Release (latest)
        id: docker_build_frontend_release
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch == 'main'
        with:
          context: .
          # file: frontend.Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
